#!/bin/bash -e

script_completed=false
trap '$script_completed || err FAILED: internal error.' 0
err()   { echo 1>&2 "$@"; script_completed=true; exit 1; }

usage() { err "Usage: $0 <login-name>"; }

[ -z "$1" ] && usage
user="$1"; shift
[ -n "$1" ] && usage


[ $(id -u) = 0 ] || err "$0 must be run as root."

#id -u "$user" || useradd "$user"

script_completed=true
